/**
 * Skill: post-review
 *
 * Aggregates all per-file reviews and posts a single GitHub PR review.
 * Uses the GitHub Reviews API to submit the feedback.
 */

import { z } from 'zod';
import { TransformSkill } from '@flomatai/core';
import type { FileReview } from './review-file.js';

export const PostReviewInputSchema = z.object({
  owner: z.string(),
  repo: z.string(),
  prNumber: z.number(),
  commitSha: z.string(),
  token: z.string(),
  prTitle: z.string(),
  reviews: z.array(z.record(z.unknown())),
});

export const PostReviewOutputSchema = z.object({
  reviewId: z.number(),
  url: z.string(),
  state: z.string(),
  filesReviewed: z.number(),
  issuesFound: z.number(),
  approved: z.boolean(),
});

export const postReviewSkill = TransformSkill.create({
  name: 'post-review',
  description: 'Aggregates file reviews and posts a GitHub PR review comment',
  inputSchema: PostReviewInputSchema,
  outputSchema: PostReviewOutputSchema,

  transform: async (input) => {
    const { owner, repo, prNumber, commitSha, token, reviews, prTitle } = input;
    const fileReviews = reviews as FileReview[];

    // Determine overall approval
    const hasErrors = fileReviews.some((r) => r.severity === 'error');
    const hasWarnings = fileReviews.some((r) => r.severity === 'warning');
    const overallApproved = !hasErrors && fileReviews.every((r) => r.approved);
    const state = overallApproved ? 'APPROVE' : hasErrors ? 'REQUEST_CHANGES' : 'COMMENT';

    // Build the review body
    const issueCount = fileReviews.reduce((n, r) => n + r.comments.length, 0);
    const severityEmoji = { error: '🔴', warning: '🟡', info: '🟢' };

    const body = [
      `## flomatai Code Review — "${prTitle}"`,
      '',
      `**Files reviewed:** ${fileReviews.length} | **Issues found:** ${issueCount}`,
      overallApproved ? '**Verdict: ✅ Approved**' : hasErrors ? '**Verdict: ❌ Changes Requested**' : '**Verdict: 💬 Comments**',
      '',
      '### Per-file Summary',
      '',
      ...fileReviews.map((r) =>
        `- ${severityEmoji[r.severity]} \`${r.filename}\` — ${r.summary}`,
      ),
      '',
      '### Detailed Findings',
      '',
      ...fileReviews.flatMap((r) =>
        r.comments.length === 0
          ? []
          : [
              `**\`${r.filename}\`**`,
              ...r.comments.map((c) =>
                `- ${severityEmoji[c.severity]}${c.line ? ` Line ${c.line}:` : ''} ${c.body}`,
              ),
              '',
            ],
      ),
      '_Review generated by [flomatai](https://github.com/AliHPlus/flomatai)_',
    ].join('\n');

    // Build inline comments for the GitHub API
    const inlineComments = fileReviews.flatMap((r) =>
      r.comments
        .filter((c) => c.line !== undefined)
        .map((c) => ({
          path: r.filename,
          position: c.line,
          body: `${severityEmoji[c.severity]} ${c.body}`,
        })),
    );

    // Post the review
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/pulls/${prNumber}/reviews`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
          'User-Agent': 'flomatai-pr-review/0.1',
        },
        body: JSON.stringify({
          commit_id: commitSha,
          body,
          event: state,
          comments: inlineComments,
        }),
      },
    );

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`GitHub review API error ${res.status}: ${text}`);
    }

    const review = await res.json() as Record<string, unknown>;

    return {
      reviewId: Number(review['id'] ?? 0),
      url: String(review['html_url'] ?? ''),
      state,
      filesReviewed: fileReviews.length,
      issuesFound: issueCount,
      approved: overallApproved,
    };
  },
});
