/**
 * ETL + Python Analysis Pipeline — runner script.
 *
 * Usage:
 *   # Use bundled synthetic data (default):
 *   node dist/src/run.js
 *
 *   # Use your own data files:
 *   node dist/src/run.js --sales ./data/sales.csv --users ./data/users.json --metrics ./data/metrics.json
 *
 *   # Save report to file:
 *   node dist/src/run.js --output ./report.md
 */

import { writeFile } from 'fs/promises';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { etlAnalysisPipeline } from './pipeline.js';
import { orchestrator } from './orchestrator.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '../data');

function getArg(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  return idx !== -1 ? process.argv[idx + 1] : undefined;
}

async function main() {
  const salesCsv = getArg('--sales') ?? process.env['SALES_CSV'] ?? join(DATA_DIR, 'sales.csv');
  const usersJson = getArg('--users') ?? process.env['USERS_JSON'] ?? join(DATA_DIR, 'users.json');
  const metricsJson = getArg('--metrics') ?? process.env['METRICS_JSON'] ?? join(DATA_DIR, 'metrics.json');
  const outputPath = getArg('--output') ?? process.env['OUTPUT'];
  const period = getArg('--period') ?? process.env['PERIOD'] ?? 'Q1 2024';

  console.log('\nData sources:');
  console.log(`  Sales:   ${salesCsv}`);
  console.log(`  Users:   ${usersJson}`);
  console.log(`  Metrics: ${metricsJson}`);
  console.log(`  Period:  ${period}`);

  try {
    const { output } = await orchestrator.run(etlAnalysisPipeline, {
      salesCsv,
      usersJson,
      metricsJson,
      period,
    });

    const report = output as {
      executiveSummary: string;
      salesHighlights: string;
      userHighlights: string;
      systemHighlights: string;
      recommendations: string[];
      riskFlags: string[];
    };

    const markdown = [
      `# Business Intelligence Report — ${period}`,
      '',
      '## Executive Summary',
      '',
      report.executiveSummary,
      '',
      '## Sales Performance',
      '',
      report.salesHighlights,
      '',
      '## User Metrics',
      '',
      report.userHighlights,
      '',
      '## System Health',
      '',
      report.systemHighlights,
      '',
      '## Recommendations',
      '',
      ...report.recommendations.map((r) => `- ${r}`),
      '',
      ...(report.riskFlags.length > 0 ? [
        '## Risk Flags',
        '',
        ...report.riskFlags.map((r) => `- ⚠️ ${r}`),
        '',
      ] : []),
      `_Report generated by flomatai on ${new Date().toISOString()}_`,
    ].join('\n');

    if (outputPath) {
      await writeFile(outputPath, markdown, 'utf-8');
      console.log(`\n✓ Report saved: ${outputPath}`);
    } else {
      console.log('\n── Report ─────────────────────────────────────────────');
      console.log(markdown);
      console.log('────────────────────────────────────────────────────────');
    }
  } catch (err) {
    console.error('\nPipeline failed:', err instanceof Error ? err.message : err);
    process.exit(1);
  }
}

main().catch(console.error);
